trigger:
  - master

pool:
  vmImage: 'macos-latest'

variables:
  - group: nexus-credentials

steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m --info'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'publishLibraryPublicationToMavenRepository'
    env:
      NEXUS_USERNAME: $(nexus_username)
      NEXUS_PASSWORD: $(nexus_password)

  - task: CopyFiles@2
    inputs:
      contents: '**/*.aar'
      targetFolder: '$(build.artifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
