/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id
 * @property tag
 */
@JsonClass(generateAdapter = true)
data class Tag(
    @Json(name = "id") @field:Json(name = "id") var id: String,
    @Json(name = "tag") @field:Json(name = "tag") var tag: String
)
