---
name: build

on:
  push:
  pull_request:

jobs:
  pmd_scan:
    name: "PMD Scan"
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'pull_request' &&
      !contains(github.event.head_commit.message, '[skip pmd]') &&
      !contains(github.event.head_commit.message, '[force]')
    steps:
      - uses: Alfresco/ya-pmd-scan@v2.0.2
        with:
          fail-on-new-issues: "false"
          create-github-annotations: "false"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18

      - uses: actions/cache@v3
        name: Cache gradle
        with:
          path: |
            ~/.m2
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: ./gradlew assembleRelease

      - name: Publish
        if: github.ref == 'refs/heads/main'
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: ./gradlew publishLibraryPublicationToMavenRepository

      - name: Store Artifact
        uses: actions/upload-artifact@v3
        with:
          name: libs
          path: ./*/build/outputs/aar/*.aar
